###                                                          ASSIGNMENT:1

In [2]:
import numpy as np

### Q.1 Write a NumPy program to create an array of integers from 30 to 70.

In [4]:
x=np.array(range(30,70))
print(x)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

###  Q.2 Write a NumPy program to create an array of all even integers from 40 to 139.

In [5]:
y=np.array(range(40,139,2))
print(y)

[ 40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74
  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108 110
 112 114 116 118 120 122 124 126 128 130 132 134 136 138]


### Q.3 Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.

In [42]:
A = np.zeros(10,dtype=int) 
print(A)
print(A.ndim)
A = np.ones(10)
print(A)
print(A.ndim)
A=np.zeros(10) +5
print(A)
print(A.ndim)

[0 0 0 0 0 0 0 0 0 0]
1
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
1
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
1


### Q.4 Write a NumPy program to create a 3x3 identity matrix.

In [13]:
a=np.eye(3,dtype=int)
print(a.ndim)
print(a)

2
[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Q.5 Write a NumPy program to create a given matrix.

In [18]:
b=np.array(range(1,21))
print(b)
print(b.ndim)
c=b.reshape(4,5)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### Q.6 Write a NumPy program to print above matrix in reverse order.(20 to 1)

In [40]:
matrix=np.array(range(20,0,-1))
print(matrix)
print(matrix.ndim)
z=matrix.reshape(4,5)
print(z)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
1
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


### Q.7 Write a program to pick any 3 random values from 100 to 300.

In [24]:
a=np.random.choice(range(100,301),3)
print("random value=",a)

random value= [218 134 185]


### Q.8 Write a program to pick any random three names from given List
.
A=[‘SACHIN’,’VIRAT’,’DHONI’,’ROHIT’,’DRAVID’,’GANGOLY’]

In [35]:
name=['SACHIN',"VIRAT","DHONI","ROHIT","DRAVID","GANGOLY"]
ab=np.random.choice(name,3)
print(ab)

['ROHIT' 'ROHIT' 'DRAVID']


### ASSIGNMENT:2

In [12]:
import numpy as np

 Q.1 Create a 3×3 NumPy array of all True.

In [39]:
x=np.full((3,3),True)
print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Q.2 Create a 1D array of 10 evenly spaced values between 5 and 50.

In [13]:
a=np.array(range(5,51,)10)
print(a)
print(a.ndim)

[ 5 10 15 20 25 30 35 40 45 50]
1


Q.3 Write a code to convert 1D array into 3D.And find it’s transpose
matrix.
Input: A=[1,2,3,4,5,5,6,7,8,9,10,12]


In [72]:
A = np.array([1,2,3,4,5,5,6,7,8,9,10,12])
arr3d = A.reshape(2, 2, 3)
print("3D Array:")
print(arr3d)

print("\nTranspose:")
print(arr3d.transpose())

3D Array:
[[[ 1  2  3]
  [ 4  5  5]]

 [[ 6  7  8]
  [ 9 10 12]]]

Transpose:
[[[ 1  6]
  [ 4  9]]

 [[ 2  7]
  [ 5 10]]

 [[ 3  8]
  [ 5 12]]]


Q.4 Create 4 ×4 Identity Matrix,and replace the diagonal value with 12.

In [70]:
a=np.eye(4,dtype=int)
np.fill_diagonal(a, 12)
print(a)

[[12  0  0  0]
 [ 0 12  0  0]
 [ 0  0 12  0]
 [ 0  0  0 12]]


Q.5 Write a code to edit the value 40 by 400 in given 1D array Input: A=[20,30,40,50,60]


In [65]:
a=np.array([20,30,40,50,60])
A[A == 40] = 400
print(a)
print(a.ndim)

[20 30 40 50 60]
1


Q.6 Write a code to update the each value by it’s square in given 2D
array
Input: A=[[20,30],[40,50],[60,70]]


In [64]:
A = np.array([[20,30],[40,50],[60,70]])
A = A**2
print(A)

[[ 400  900]
 [1600 2500]
 [3600 4900]]


Q.7 Write a code to delete 50 in given 1D array.
Input: A=[20,30,40,50,60].

In [61]:
A = np.array([20,30,40,50,60])
A = np.delete(A, 3)
print(A)

[20 30 40 60]


Q.8 Write a code to insert 48 in 3 rd indexing in given 1D array.
Input: A=[20,30,40,50,60]


In [62]:
A = np.array([20,30,40,50,60])
A = np.insert(A, 3, 48)
print(A)

[20 30 40 48 50 60]


Q.9 Write a code to find odd number in given 1D array.
Input: A=[20,3,7,80,89]

In [46]:
a=np.array([20,3,7,80,89])
b = a[a%2 != 0]
print(b)

[ 3  7 89]


Q.10 Write a code to replace 0 by 99 in identity matrix.

In [74]:
a=np.eye(3,dtype=int)
print(a.ndim)
a[a == 0] = 99
print(a)

2
[[ 1 99 99]
 [99  1 99]
 [99 99  1]]


###                                                          ASSIGNMENT:3

In [2]:
import numpy as np

In [6]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[:4:])

[10 20 30 40]


In [29]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[4:2])

[]


In [10]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[4:])

[50 60 70 80]


In [27]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[:4:3])

[10 40]


In [11]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[-1:])

[80]


In [12]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[-4:])

[50 60 70 80]


In [13]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[-6:])

[30 40 50 60 70 80]


In [26]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[:-3:-1])

[80 70]


In [25]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[-8:])

[10 20 30 40 50 60 70 80]


In [24]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[:6:2])

[10 30 50]


In [23]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[:-6:-2])

[80 60 40]


In [22]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[:-3:2])

[10 30 50]


In [19]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[:-5:-1])

[80 70 60 50]


In [21]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[:-5:-3])

[80 50]


In [30]:
n=np.array([10,20,30,40,50,60,70,80])
print(n[:-5:3])

[10]


In [31]:
a=np.ones(25,dtype=int).reshape(5,5)
a[1:4,1:4] = 0
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
