In [2]:
import numpy as np

### 1. Create a 2D array with 1 on border and 0 on inside.

In [107]:
a=np.ones(100,dtype=int).reshape(10,10)
a[1:9,1:9] = 0
print(a)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### 2. Find indices of Non-zero elements from A[2,3,0,1,0,9].

In [32]:
A = np.array([2, 3, 0, 1, 0, 9])
B = np.nonzero(A)
print(B[0])

[0 1 3 5]


### 3. Create a zero one D vector of size 10 but 5 th indexing value should be replaced by 9.

In [35]:
A = np.zeros(10)
A[4]= 9
print(A)


[0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]


### 4. Create a 3×3 NumPy array of all True.


In [18]:
A=np.full((3,3),True)
print(A)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### 5. Create a 4×4 array and extract its first row and last column.


In [70]:
AB = np.array(range(16)).reshape(4,4)
print(AB)
print(AB[0,:])
print(AB[:,3])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[ 3  7 11 15]


## 6. Sorting a Numpy array with descending order.


In [89]:
A=np.array([20,304,84,20,3,24,5,6,7,2,456,478,4])
np.sort(A)[::-1]
# np.sort(A)

array([478, 456, 304,  84,  24,  20,  20,   7,   6,   5,   4,   3,   2])

### 7. Sorting a NumPy array based on a specific column.
 Ex: Array = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]]
Note:(Sort records of 2 nd column) 

In [116]:
Array = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]]
                 

### 8. Replace all odd numbers in a NumPy array with -1.

In [3]:
B=np.array([1,2,3,4,5,6,7,8,91,20,30,12,14,16,34,67,54,44,22,88,98,99,53,21,2])
# B[B%3==0]=-1
B[B % 2 != 0] = -1
print(B)

[-1  2 -1  4 -1  6 -1  8 -1 20 30 12 14 16 34 -1 54 44 22 88 98 -1 -1 -1
  2]


### 9. Create a 1D array of 10 evenly spaced values between 5 and 50

In [52]:
A = np.linspace(5, 50, 10,dtype=int)
print(A)

[ 5 10 15 20 25 30 35 40 45 50]


### 10. Remove common items from array
 Input A1=[1,2,3,4,5]
 A2=[1,4,7,8,5]
 Output=[2,3,7,8]

In [26]:
A1=[1,2,3,4,5] 
A2=[1,4,7,8,5]
A3 = np.setxor1d(A1, A2)
print(A3)

[2 3 7 8]


### 11. Get the positions where elements of array a and b match
Input A1=[1,2,3,4,5]
A2=[1,7,8,4,5]
Output=array([0,3,4])


In [47]:
A1=np.array([1,2,3,4,5])
A2=np.array([1,7,8,4,5])
C = np.where(A1 == A2)
print(C[0])

[0 3 4]


### 12 Create a random 3×2 matrix and find its maximum and minimum values.
Input A1=[[1,2,3,4,5],[0,8,7,9,6]]
Output:min=0
Max=9

In [9]:
A1=[[1,2,3,4,5],[0,8,7,9,6]] 
np.max([A1])
# np.min([A1])

np.int64(9)

### 13 Delete second column from given array.
Input A1=[[1,2,3,4,5],[0,8,7,9,6]]
Output:[[1,2,4,5],[0,8,9,6]]


In [10]:
A1=[[1,2,3,4,5],[0,8,7,9,6]]
A1 = np.delete(A1,2,axis=1)
print(A1)

[[1 2 4 5]
 [0 8 9 6]]


### 14. Split a 1D array of 9 elements into 3 equal parts

In [24]:
arr = np.arange(9)
print(arr)
a = np.split(arr, 3)
print(a)

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


### 15. Check if an array contains any NaN values.

In [3]:
A=[12,23,np.nan]
print(A)
o=np.array(A)
print(o)

[12, 23, nan]
[12. 23. nan]
