In [2]:
import numpy as np
# import pandas as pd

In [2]:
A=[1,2,3,4]
print(A)
print(A[3])

[1, 2, 3, 4]
4


In [3]:
A=[[1,2,3,4]]
print(A[0][3])

4


In [4]:
B=[[1,2],[3,4]]
B

[[1, 2], [3, 4]]

In [5]:
d = {"rno":[1,2,3,4],"marks": [89,45,6,5]}
d
print("done")
print(d["marks"][3])
# array 2 type ke hote hai
# 1 numeric array -- ye hack ho jata hai 
# 2 associative array -- ahi hota hack
print(d["marks"][1])

done
5
45


In [6]:
a = 90
print(id(a))

140721618857672


In [7]:
 v=np.array(range(1,11))
 print(v)        

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
X=np.array(range(0,100,10))
print(X)

[ 0 10 20 30 40 50 60 70 80 90]


In [9]:
v=np.array(range(1,11,2))
print(v)  

[1 3 5 7 9]


In [10]:
v=np.array(range(2,11,2))
print(v) 

[ 2  4  6  8 10]


In [11]:
v=np.array(range(10,1,-1))
print(v) 

[10  9  8  7  6  5  4  3  2]


In [12]:
v=np.array(range(10,1,-2))
print(v) 

[10  8  6  4  2]


In [13]:
v=np.array(range(10,1,-2))
print(v) 

[10  8  6  4  2]


In [14]:
v=np.array(range(99,1,-3))
print(v) 

[99 96 93 90 87 84 81 78 75 72 69 66 63 60 57 54 51 48 45 42 39 36 33 30
 27 24 21 18 15 12  9  6  3]


In [15]:
# reshape (): With the help of reshape (), we can convert 1D array into multi Dimmension and vice versa
# reshape () convert lower dimension array into hoigher dimension array and vice versa

In [16]:

A = np.array(range(1,11))
print(A)
print(A.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1


In [17]:
A = np.array([[1,2,3,4,5,6,7,8,9,10]])
print(A)
print(A.ndim)

[[ 1  2  3  4  5  6  7  8  9 10]]
2


In [18]:
A = np.array([[[1,2,3,4,5,6,7,8,9,10]]])
print(A)
print(A.ndim)

[[[ 1  2  3  4  5  6  7  8  9 10]]]
3


In [19]:
A = np.array([1,2,3,4,5,6,7,8,9,10])
print(A)
print(A.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1


In [20]:
A=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
B=A.reshape(2,10)
print(B)
print(A.ndim)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
1


In [21]:
A = np.array([1,2,3,4,5,6,7,8,9,10])
print(A)
print(A.ndim)
B=A.reshape(2,5)
print(B)
print(B.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [22]:
A = np.array([1,2,3,4,5,6,7,8,9,10])
print(A)
B=A.reshape(5,2)
print(B)
print(B.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2


In [23]:
# convert lower dimension into higher dimension
A=np.array([1,2,3,4,5,6,7,8,9,10])
print(A)
print(A.ndim)
B=A.reshape(5,2) # two dimension reshape(raw,col)
print(B)
print(B.ndim)
C=A.reshape(1,5,2) #three dimension (table,raw,col)
print(C)
print(C.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
1
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]]
3


###  Convert Higher Dimension into Lower dimension

In [24]:
A =np.array([[10,20,30],[40,50,60],[70,80,90]])
print(A)
print(A.ndim)
B=A.reshape(9)
print(B)
print(B.ndim)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
2
[10 20 30 40 50 60 70 80 90]
1


In [25]:
A=np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print(A)
print(A.ndim)

[[[10 20 30]
  [40 50 60]
  [70 80 90]]]
3


In [26]:
B=A.reshape(3,3)
print(B)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [27]:
B=A.reshape(3,3)
B

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [28]:
B=A.reshape(1,9)
print(B)

[[10 20 30 40 50 60 70 80 90]]


In [29]:
B=A.reshape(1,9)
print(B)

[[10 20 30 40 50 60 70 80 90]]


In [30]:
B=A.reshape(9)
print(B)


[10 20 30 40 50 60 70 80 90]


In [31]:
A = np.zeros(5) #1d
print(A)
print(A.ndim)
A = np.zeros((2,5)) #2D
print(A)
print(A.ndim)
A=np.zeros((2,3,2)) #3D
print(A)
print(A.ndim)

[0. 0. 0. 0. 0.]
1
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
3


In [32]:
A = np.zeros(5) +5 #1d
print(A)
print(A.ndim)
A = np.zeros((2,5)) +6#2D
print(A)
print(A.ndim)
A=np.zeros((2,3,2)) -8#3D
print(A)
print(A.ndim)

[5. 5. 5. 5. 5.]
1
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
2
[[[-8. -8.]
  [-8. -8.]
  [-8. -8.]]

 [[-8. -8.]
  [-8. -8.]
  [-8. -8.]]]
3


In [33]:
A = np.ones(7 ,dtype=int)
print(A)
print(A.ndim)
A=np.ones(5) #1D
print(A)

[1 1 1 1 1 1 1]
1
[1. 1. 1. 1. 1.]


In [34]:
A = np.ones(5) #1d
print(A)
print(A.ndim)
A = np.ones((2,5)) #2D
print(A)
print(A.ndim)
A=np.ones((2,3,4)) #3D
print(A)
print(A.ndim)
A=np.ones((2,3,4),dtype = int) #3D
print(A)
print(A.ndim)

[1. 1. 1. 1. 1.]
1
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
3


### IDENTITY MATRIX OR ALL DIAGONAL VALUEW IS 1

In [35]:
# IENTITY MATRIX OR ALL DIAGONAL VALUEW IS 1
# symmetric
W=np.eye(7) #(n*n)
print(W)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [36]:
W=np.eye(10) #(n*n)
W[1:11:,0:2:] = 1
print(W)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [37]:
R = np.arange(5)
print(R)

[0 1 2 3 4]


In [38]:
R = np.arange(2,8)
print(R)

[2 3 4 5 6 7]


In [39]:
R = np.arange(8)
print(R)
s=R.reshape(2,4)
print(s)


[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [40]:
d=R.reshape(4,2) # (row,col)2d
print(d)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [41]:
g= np.arange(8)
print(g)
R=g.reshape(2,4) # (table,row,col)3d
print(R)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [42]:
K= np.random.choice(8)
print(K)

6


In [43]:
K= np.random.choice(8,3)
print(K)

[5 4 0]


In [44]:
K= np.random.choice(7,8)
print(K)

[4 6 5 5 1 0 4 2]


In [45]:
DICE= np.random.choice(7) #player 1
print("result=",DICE)

result= 6


In [46]:
game= np.random.choice(6,2) #player 2
print("result=",game)

result= [3 5]


In [47]:
t=[1,2,3,4,5]
A=np.random.choice(t)
print(A)
t=[1,2,3,4,5]
A=np.random.choice(t,3)
print(A)
Name=["Anuraj","manaya","Abhaya","Rime","Rahul","Ajay"]
k=np.random.choice(Name,2)
print(k)

1
[1 3 2]
['Abhaya' 'Ajay']


In [48]:
Name=["Anuraj","manaya","Abhaya","Rime","Rahul","Ajay"]
l=np.random.choice(Name,4)
print(l)

['Rahul' 'Abhaya' 'Abhaya' 'Ajay']


In [49]:
A=np.random.rand(30) #it always return decimal value between 0 to 1
print(A) 

[0.45203488 0.73166087 0.14378349 0.50349391 0.38239214 0.43952552
 0.04944654 0.21473487 0.89733533 0.12017723 0.55788312 0.65777016
 0.65906309 0.74891513 0.86697929 0.80668934 0.40016383 0.24810664
 0.18303149 0.90432121 0.57238793 0.85698638 0.56852948 0.4167221
 0.99415353 0.63761007 0.5974213  0.83953557 0.81377322 0.38624239]


In [50]:
B=np.random.randint(90)
print(B)

89


In [51]:
s=np.linspace(1,10,5,dtype=int,retstep=True)
print(s)
               

(array([ 1,  3,  5,  7, 10]), np.float64(2.25))


In [52]:
# 1 insert the value using index
# 2 Delete the value using index
# 3 Append the value.
A = np.array([10,30,4,56,7,8,90,21])
print(A)
#np.insert(A,3,200) #insert (arrayname,index,value)change  temporary 
A=np.insert(A,3,200) # permanent change
print(A)
A=np.append(A,300)
print(A)
A=np.append(A,987)
print(A)


[10 30  4 56  7  8 90 21]
[ 10  30   4 200  56   7   8  90  21]
[ 10  30   4 200  56   7   8  90  21 300]
[ 10  30   4 200  56   7   8  90  21 300 987]


In [53]:
A = np.array([10,30,4,56,7,8,90,21])
print(A)
A=np.delete(A,4) # delete(arrayname,indexpostion)
print(A)


[10 30  4 56  7  8 90 21]
[10 30  4 56  8 90 21]


In [54]:
B = np.array([10,30,4,56,7,8,90,21])  #1D
print(B)
np.delete(B,[0,3,5])

[10 30  4 56  7  8 90 21]


array([30,  4,  7, 90, 21])

In [55]:
B = np.array([[10,30],[4,56],[7,8]])  #1D
print(B)
np.delete(B,1,axis=0)
np.delete(B,1,axis=1)

[[10 30]
 [ 4 56]
 [ 7  8]]


array([[10],
       [ 4],
       [ 7]])

In [56]:
c=np.array([[10,20],[30,40],[50,60]])+100
print(c)

[[110 120]
 [130 140]
 [150 160]]


In [57]:
c=np.array([[10,20],[30,40],[50,60]])
c=c+100
print(c)

[[110 120]
 [130 140]
 [150 160]]


In [58]:
c=np.array([[10,20,1],[30,40,2],[50,60,3]])
print(c)
print("row and column=",c.shape)
print("total length=",c.size)
print("dimension=",c.ndim)
#transpose matrix
t=np.transpose(c)
print(t)
print(t.shape)

[[10 20  1]
 [30 40  2]
 [50 60  3]]
row and column= (3, 3)
total length= 9
dimension= 2
[[10 30 50]
 [20 40 60]
 [ 1  2  3]]
(3, 3)


In [59]:
#transpose matrix
t=np.transpose(c)
print(t)
print(t.shape)

[[10 30 50]
 [20 40 60]
 [ 1  2  3]]
(3, 3)


### DATE => 1-6-26 slicing

In [60]:
A=np.array([2,3,4,5,7])
print(A) 
B=A[0:2]
print(B)
C=A[0:4:2]
print("print C=", C)

[2 3 4 5 7]
[2 3]
print C= [2 4]


In [61]:
c= np.array([10,20,30,40,50,60,70,90,100])
D=c[2:8:3]
print(D)

[30 60]


In [62]:
c= np.array([10,20,30,40,50,60,70,90,100])
D=c[:-1:]
e=c[:-2:]
print(D)
print(e)
k=c[:-5:]
print(k)

[10 20 30 40 50 60 70 90]
[10 20 30 40 50 60 70]
[10 20 30 40]


In [63]:
c= np.array([10,20,30,40,50,60,70,90,100])
D=c[::-1]
print(D)

[100  90  70  60  50  40  30  20  10]


In [64]:
c= np.array([10,20,30,40,50,60,70,90,100])
D=c[-5::-1]
print(D)

[50 40 30 20 10]


In [65]:
c= np.array([10,20,30,40,50,60,70,90,100])
D=c[-3::-1]
print(D)

[70 60 50 40 30 20 10]


In [66]:
c= np.array([10,20,30,40,50,60,70,90,100])
D=c[::-2]
print(D)

[100  70  50  30  10]


In [67]:
c= np.array([10,20,30,40,50,60,70,90,100])
D=c[-2:-6:-1]
print(D)

[90 70 60 50]


In [68]:
c=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(c)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [69]:
a=np.array(range(1,17))
print(a)
b=a.reshape(4,4)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [70]:
a=np.array(range(1,17)).reshape(4,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [71]:
a=np.array(range(1,17)).reshape(4,4)
print(a)
a[2:4,1:3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[10, 11],
       [14, 15]])

In [72]:
a=np.array(range(1,17)).reshape(4,4)
print(a)
a[1:2,1:4]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[6, 7, 8]])

In [73]:
a=np.array(range(1,17)).reshape(4,4)
print(a)
a[0:2,1:3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[2, 3],
       [6, 7]])

In [74]:
a=np.array(range(1,17)).reshape(4,4)
print(a)
a[0:5,0:1]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [75]:
a=np.array(range(1,17)).reshape(4,4)
print(a)
a[3:4,3:4]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[16]])

In [76]:
A=np.array([1,2,3,4,5])
B=np.array([10,20,30,40,50])
print(A*B)
np.dot(A,B)

[ 10  40  90 160 250]


np.int64(550)

In [77]:
A=np.array([[8,2,4]])
B=np.array([[6,2,3]])
np.cross(A,B)

array([[-2,  0,  4]])

### mathematical operation 

In [78]:
A=np.array([10,20,30])
B=np.array([4,6,7])
np.add(A,B) # Broadvasting universal Function
np.subtract(A,B)

array([ 6, 14, 23])

In [79]:
A=np.array([[10,20,30],[1,2,3]])
B=np.array([[4,6,7],[100,200,300]])
print(A)
print(B)
np.add(A,B)
np.subtract(A,B)
np.multiply(A,B)
np.divide(A,B)

[[10 20 30]
 [ 1  2  3]]
[[  4   6   7]
 [100 200 300]]


array([[2.5       , 3.33333333, 4.28571429],
       [0.01      , 0.01      , 0.01      ]])

In [80]:
A=np.array([[10,20,30],[1,2,3]])
B=np.array([[4,6,7],[100,200,300]])
print(A)
print(B)
np.add(A,B)

[[10 20 30]
 [ 1  2  3]]
[[  4   6   7]
 [100 200 300]]


array([[ 14,  26,  37],
       [101, 202, 303]])

In [81]:
A=np.array([[10,20,30],[1,2,3]])
B=np.array([[4,6,7],[100,200,300]])
print(A)
print(B)
np.subtract(A,B)

[[10 20 30]
 [ 1  2  3]]
[[  4   6   7]
 [100 200 300]]


array([[   6,   14,   23],
       [ -99, -198, -297]])

In [82]:
A=np.array([[10,20,30],[1,2,3]])
B=np.array([[4,6,7],[100,200,300]])
print(A)
print(B)
np.multiply(A,B)

[[10 20 30]
 [ 1  2  3]]
[[  4   6   7]
 [100 200 300]]


array([[ 40, 120, 210],
       [100, 400, 900]])

In [83]:
A=np.array([[10,20,30],[1,2,3]])
B=np.array([[4,6,7],[100,200,300]])
print(A)
print(B)
np.divide(A,B)

[[10 20 30]
 [ 1  2  3]]
[[  4   6   7]
 [100 200 300]]


array([[2.5       , 3.33333333, 4.28571429],
       [0.01      , 0.01      , 0.01      ]])

In [84]:
Q=np.array([10,20,30,40,20,203,9,12,45])
np.sum(Q)

np.int64(389)

In [85]:
Q=np.array([10,20,30,40,20,203,9,12,45])
np.max(Q)

np.int64(203)

In [86]:
Q=np.array([10,20,30,40,20,203,9,12,45])
np.min(Q)

np.int64(9)

In [87]:
Q=np.array([10,20,30,40,20,203,9,12,45])
np.mean(Q)

np.float64(43.22222222222222)

In [88]:
Q=np.array([10,20,30,40,20,203,9,12,45])
np.std(Q)

np.float64(57.77884614396859)

In [89]:
Q=np.array([10,20,30,40,20,203,9,12,45])
np.var(Q)

np.float64(3338.3950617283945)

In [90]:
Q=np.array([10,20,30,40,20,203,9,12,45])
np.sort(Q)

array([  9,  10,  12,  20,  20,  30,  40,  45, 203])

In [91]:
Q=np.array([10,20,30,40,20,203,9,12,45])
np.sort(Q)[::-1]

array([203,  45,  40,  30,  20,  20,  12,  10,   9])

In [92]:
S=np.array([2,5,3,4,9,7])
np.sqrt(S)

array([1.41421356, 2.23606798, 1.73205081, 2.        , 3.        ,
       2.64575131])

In [93]:
A=np.array([2])
np.sqrt(A)

array([1.41421356])

In [94]:
import numpy as np

In [95]:
a=np.ones(25,dtype=int).reshape(5,5)
a[1:4,1:4] = 0
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [96]:
a=np.ones(25,dtype=int).reshape(5,5)
a[1:4,1:5] = 2
a[2:4,1:5] = 3
a[3:4,1:5] = 4
print(a)

[[1 1 1 1 1]
 [1 2 2 2 2]
 [1 3 3 3 3]
 [1 4 4 4 4]
 [1 1 1 1 1]]


In [97]:
A=np.array([[8,2,4]])
B=np.array([[6,2,3]])
np.cross(A,B)

array([[-2,  0,  4]])

In [98]:
A1 = np.array([1,4,5])
B1 = np.array([7,5,6])
print(A1,B1)

[1 4 5] [7 5 6]


In [99]:
A1@B1 # matrix

np.int64(57)

## Where Function

In [100]:
arr = np.array([10,20,30,2,45])
result = np.where(arr > 20)
print(result)


(array([2, 4]),)


In [101]:
arr = np.array([10,20,30,2,45])
result = np.where(arr%2==0)
print(result)

(array([0, 1, 2, 3]),)


In [102]:
arr = np.array([10,20,30,2,45])
for i in range(len(arr)):
    print(arr[i])

10
20
30
2
45


In [103]:
arr = np.array([10,20,30,2,45])
for i in (arr):
    print(i)

10
20
30
2
45


In [104]:
arr = np.array([2,3,4,5,6])
for i in np.nditer(arr):
    print(i)

2
3
4
5
6


In [105]:
arr = np.array([2,3,4,5,6])
for i in arr:
    print(i)

2
3
4
5
6


In [106]:
arr = np.array([[10,20,30,2,45]])
for i in np.nditer(arr):
    print(i)

10
20
30
2
45


In [107]:
arr = np.array([[2,3,4,5,6]])
for i,v in np.ndenumerate(arr):
    print(i,v)
    

(0, 0) 2
(0, 1) 3
(0, 2) 4
(0, 3) 5
(0, 4) 6


In [108]:
arr = np.array([10,20,30,45])
result = np.where(arr%2==0)
print(result)

(array([0, 1, 2]),)


In [109]:
import numpy as np

In [110]:
arr = np.array([10,20,30,45])
for i,v in np.ndenumerate(arr):
    print(i,v)

(0,) 10
(1,) 20
(2,) 30
(3,) 45


In [111]:
arr = np.array([[10,20,30,45]])
D=np.where(arr%2==0)
print(arr[D])

[10 20 30]


In [112]:
A1 = np.array([1,2,3,4])
B1 = np.array([10,20,30,40])
A1@B1

np.int64(300)

In [113]:
X1 = np.array([[1,2],[3,4]])
Y1 = np.array([[10,20],[30,40]])
X1@Y1

array([[ 70, 100],
       [150, 220]])

In [114]:
B1 = np.array([10,20,30,40,50,60,70,80]).reshape(2,4)
print(B1)
k=B1.T
print(k)

[[10 20 30 40]
 [50 60 70 80]]
[[10 50]
 [20 60]
 [30 70]
 [40 80]]


In [115]:
A=np.eye(3)
A[A==0]=2
print(A)

[[1. 2. 2.]
 [2. 1. 2.]
 [2. 2. 1.]]


In [116]:
A=np.eye(3)+2
print(A)

[[3. 2. 2.]
 [2. 3. 2.]
 [2. 2. 3.]]


In [117]:
A=np.array([4,5,2,5,2,1,4,5,2,4,3,2,4,2,3,4])
print(A)
np.unique(A) # display unique data with sorted 
A1 = np.array([0,0,9,8,7,0,0])
print(A1)
np.trim_zeros(A1)          # trim zero from both sides
np.trim_zeros(A1,trim='b') # trim zero from backward 
np.trim_zeros(A1,trim='f') # trim zero from front

[4 5 2 5 2 1 4 5 2 4 3 2 4 2 3 4]
[0 0 9 8 7 0 0]


array([9, 8, 7, 0, 0])

In [118]:
B1 = np.array([89,0,4,3,0,12,33])
np.count_nonzero(B1)

np.int64(5)

In [119]:
C1 = np.array([10,20,30,40,50])
D1= np.array([100,200,300,400,500])
for i in zip(C1,D1):
    print(i)

(np.int64(10), np.int64(100))
(np.int64(20), np.int64(200))
(np.int64(30), np.int64(300))
(np.int64(40), np.int64(400))
(np.int64(50), np.int64(500))


In [120]:
C1 = np.array([10,20,30,40,50])
D1= np.array([100,200,300,400,500,700])
for i in zip(C1,D1):
    print(i)

(np.int64(10), np.int64(100))
(np.int64(20), np.int64(200))
(np.int64(30), np.int64(300))
(np.int64(40), np.int64(400))
(np.int64(50), np.int64(500))


In [121]:
C1 = np.array([10,20,30,40,50,60])
D1= np.array([100,200,300,400,500])
for i in zip(C1,D1):
    print(i)

(np.int64(10), np.int64(100))
(np.int64(20), np.int64(200))
(np.int64(30), np.int64(300))
(np.int64(40), np.int64(400))
(np.int64(50), np.int64(500))


In [122]:
C1 = np.array([10,20,30,40,50])
D1= np.array([100,200,300,400,500])
for i,j in zip(C1,D1):
    print(i,j)

10 100
20 200
30 300
40 400
50 500


In [123]:
C1 = np.array([10,20,30,40,50])
D1= np.array([100,200,300,400,500])
for i,j in zip(C1,D1):
    print(i+j)

110
220
330
440
550


In [124]:
C1 = np.array([10,20,30,40,50])
D1= np.array([100,200,300,400,500])
for i,j in zip(C1,D1):
    print(i-j)

-90
-180
-270
-360
-450


In [125]:
C1 = np.array([10,20,30,40,50])
D1= np.array([100,200,300,400,500])
for i,j in zip(C1,D1):
    print(i*j)

1000
4000
9000
16000
25000


In [126]:
C1 = np.array([10,20,30,40,50])
D1= np.array([100,200,300,400,500])
E1= np.array([60,65,70,75,80])
for i,j,k in zip(C1,D1,E1):
    print(i,j,k)

10 100 60
20 200 65
30 300 70
40 400 75
50 500 80


In [127]:
C1 = np.array([10,20,30,40,50])
D1= np.array([100,200,300,400,500])
E1= np.array([60,65,70,75,80])
for i,j,k in zip(C1,D1,E1):
    print(i+j+k)

170
285
400
515
630


In [128]:
C1 = np.array([10,20,30,40,50])
D1= np.array([100,200,300,400,500])
E1= np.array([60,65,70,75,80])
K = list(zip(C1,D1,E1))
print(K)

[(np.int64(10), np.int64(100), np.int64(60)), (np.int64(20), np.int64(200), np.int64(65)), (np.int64(30), np.int64(300), np.int64(70)), (np.int64(40), np.int64(400), np.int64(75)), (np.int64(50), np.int64(500), np.int64(80))]


In [129]:
C1=([10,20,30,40,50])
D1=([100,200,300,400,500])
E1=([60,65,70,75,80])
K = list(zip(C1,D1,E1))
print(K)

[(10, 100, 60), (20, 200, 65), (30, 300, 70), (40, 400, 75), (50, 500, 80)]


### intersect1d Function

In [130]:
A1=([10,2,3,4])
B1=([40,10,90,6,2])
np.intersect1d(A1,B1)

array([ 2, 10])

In [131]:
A1=([10,2,3,4])
B1=([40,10,90,6,2])
np.union1d(A1,B1)

array([ 2,  3,  4,  6, 10, 40, 90])

### setxor1d Function This is not comman

In [132]:
A1=([10,2,3,4])
B1=([40,10,90,6,2])
np.setxor1d(A1,B1)

array([ 3,  4,  6, 40, 90])

### Array_split Function

In [133]:
A=np.arange(0,100,2)
A
B= np.array_split(A,5)
B

[array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),
 array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38]),
 array([40, 42, 44, 46, 48, 50, 52, 54, 56, 58]),
 array([60, 62, 64, 66, 68, 70, 72, 74, 76, 78]),
 array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])]

In [134]:
A=np.array([10,20,30,40,50,60,70,80])
print(A)
print(A.ndim)
D=np.array_split(A,2)
print(D)

[10 20 30 40 50 60 70 80]
1
[array([10, 20, 30, 40]), array([50, 60, 70, 80])]


In [135]:
A=np.array([10,20,30,40,50,60,70,80])
# print(A)
print(A.ndim)
D=np.array_split(A,2)
# print(D)
group1=D[0]
group1
group2=D[1]
group2

1


array([50, 60, 70, 80])

In [136]:
A=np.array([10,20,30,40,50,60,70,80])
print(A)
print(A.ndim)
D=np.array_split(A,3)
print(D)

[10 20 30 40 50 60 70 80]
1
[array([10, 20, 30]), array([40, 50, 60]), array([70, 80])]


In [137]:
A=np.array([10,20,30,40,50,60,70,80])
print(A)
print(A.ndim)
D=np.array_split(A,5)
print(D)

[10 20 30 40 50 60 70 80]
1
[array([10, 20]), array([30, 40]), array([50, 60]), array([70]), array([80])]


## save and load

In [138]:
S=np.array([10,30,40,50])
print(S)
np.save("honey.npy",S)
np.load("honey.npy")

[10 30 40 50]


array([10, 30, 40, 50])

In [139]:
S=np.array([10,30,40,50])
print(S)
np.load("honey.npy")

[10 30 40 50]


array([10, 30, 40, 50])

### save and text Function

In [140]:
S=np.array([10,30,40,50])
print(S)
np.save("honey.npy",S)

[10 30 40 50]


In [141]:
import numpy as np

In [142]:
S=np.array([10,30,40,50])
print(S)
np.savetxt("look.txt",S,header="Transfer list of emp", footer="Done")

[10 30 40 50]


In [143]:
S=np.array([10,30,40,50])
print(S)
np.savetxt("deep.txt",S,header="Transfer list of emp", footer="Done")

[10 30 40 50]


In [144]:
S=np.array([10,30,40,50])
print(S)
np.savetxt("deep2.txt",S,fmt="%d",header="Transfer list of emp", footer="Done")

[10 30 40 50]


In [145]:
S=np.array([10,30,40,50])
print(S)
np.savetxt("look1.txt",S,fmt="%d",header="Transfer list of emp", footer="Done")

[10 30 40 50]


In [146]:
S=np.array([10,30,40,50])
print(S)
np.savetxt("deep2.txt",S,fmt="%d",header="Transfer list of emp", footer="Done")
np.loadtxt("deep2.txt")

[10 30 40 50]


array([10., 30., 40., 50.])

In [147]:
S=np.array([10,30,40,50])
print(S)
np.load("honey.npy")

[10 30 40 50]


array([10, 30, 40, 50])

###  isnan Function

In [148]:
A=[12,23,np.nan]
print(A)
o=np.array(A)
print(o)
np.isnan(o)

[12, 23, nan]
[12. 23. nan]


array([False, False,  True])

### View

In [149]:
X=np.array([[90,23,1,4]])
print(X)
Y=X.view()
print(Y)

[[90 23  1  4]]
[[90 23  1  4]]


In [150]:
A=np.array([10,20,30,40])
print(A)
B=A.view()
print(A)

[10 20 30 40]
[10 20 30 40]


In [151]:
import numpy as np

original = np.array([1, 2, 3, 4, 5])
arr_view = original.view()

# Modify the view
arr_view[0] = 99

print(original)  # Output: [99  2  3  4  5] (Changed!)
print(arr_view)  # Output: [99  2  3  4  5]


[99  2  3  4  5]
[99  2  3  4  5]


In [152]:
### Function

In [153]:
A=np.array([10,20,30,40])
print(A)
B=A.view()
A=np.append(A,200)
print(A)

[10 20 30 40]
[ 10  20  30  40 200]


### Copy

In [154]:
X=np.array([[90,23,1,4]])
print(X)
Y=X.copy()
print(Y)

[[90 23  1  4]]
[[90 23  1  4]]


In [155]:
A=np.array([10,20,30,40])
print(A)
B=A.copy()
print(A)

[10 20 30 40]
[10 20 30 40]


In [156]:
A=np.array([10,20,30,40])
print(A)
B=A.copy()
A=np.append(B,300)
print(A)

[10 20 30 40]
[ 10  20  30  40 300]


In [157]:
import numpy as np

original = np.array([1, 2, 3, 4, 5])
arr_copy = original.copy()

# Modify the copy
arr_copy[0] = 99

print(original)  # Output: [1 2 3 4 5]  (Unchanged)
print(arr_copy)  # Output: [99  2  3  4  5]


[1 2 3 4 5]
[99  2  3  4  5]


## # Concatenate 

In [158]:
import numpy as np

a = np.array([[1, 2]])
b = np.array([[3, 4]])

# Concatenate along rows (Axis 0)
row_joined = np.concatenate((a, b), axis=0)
# Result: 
# [[1, 2],
#  [3, 4]]

# Concatenate along columns (Axis 1)
col_joined = np.concatenate((a, b), axis=1)
# Result: [[1, 2, 3, 4]]
print(col_joined)


[[1 2 3 4]]


In [159]:
#ravel # flatten #copy #View

### flatten

In [160]:
A=np.array([[[10,20,30,40,50,60]]])
print(A)
print(A.ndim)
B=A.flatten()
print(B)
print(B.ndim)

[[[10 20 30 40 50 60]]]
3
[10 20 30 40 50 60]
1


In [161]:
A=np.array([[[10,20,30,40,50,60]]])
print(A)
print(A.ndim)
B=A.flatten()
print(B)
B[3]=400
print(B)

[[[10 20 30 40 50 60]]]
3
[10 20 30 40 50 60]
[ 10  20  30 400  50  60]


In [162]:
A=np.array([[[10,20,30,40,50,60]]])
print(A.ndim)
B=A.flatten()
np.append(B,100)
A=np.append(A,200)
print(A)
print(B)

3
[ 10  20  30  40  50  60 200]
[10 20 30 40 50 60]


### Ravel

In [163]:
A=np.array([[[10,20,30,40,50,60]]])
print(A)
print(A.ndim)
B=A.ravel()
print(B)
B[3]=400
print(B)

[[[10 20 30 40 50 60]]]
3
[10 20 30 40 50 60]
[ 10  20  30 400  50  60]


In [164]:
A=np.array([[[10,20,30,40,50,60]]])
print(A)
print(A.ndim)
B=A.ravel()
print(B)
print(B.ndim)

[[[10 20 30 40 50 60]]]
3
[10 20 30 40 50 60]
1


In [165]:
A=np.array([[[10,20,30,40,50,60]]])
print(A.ndim)
B=A.ravel()
np.append(B,100)
A=np.append(A,200)
print(A)
print(B)

3
[ 10  20  30  40  50  60 200]
[10 20 30 40 50 60]


### Full

In [166]:
A=np.full((3,3),True)
print(A)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [167]:
A=np.full((3,3),True)
print(A)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [168]:
A = np.ones((3,3),dtype=int)
A[1:2,0:1] = 0
A[0:1,1:2] = 0
A[2:3,1:2] = 0
A[1:2,2:] = 0
print(A)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [169]:
import numpy as np

In [170]:
M = np.zeros((3,3),dtype=int)
print(M)
M[::,1::2] = 1
print("New matrix")
print(M)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
New matrix
[[0 1 0]
 [0 1 0]
 [0 1 0]]


In [171]:
M = np.zeros((3,3),dtype=int)
M[::,1::2] = 1
print(M)

[[0 1 0]
 [0 1 0]
 [0 1 0]]


In [172]:
M = np.zeros((4,4),dtype=int)
print(M)
M[::,1::2] = 1
print("New matrix")
print(M)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
New matrix
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [173]:
A=np.eye(3,dtype=int)
print(A)
A[::2,::2] = 1
print("New matrix")
print(A)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
New matrix
[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [174]:
import numpy as np

In [175]:
A =np.array([2,5,8,6,7,1,12,50,99])
B=A.reshape(3,3)
B[B%2==0] = 0
print(B)


[[ 0  5  0]
 [ 0  7  1]
 [ 0  0 99]]


In [176]:
# B =np.array([5,2,5,3,2,9,1,3])
# print(B)
# print(np.unique(B)) 

In [177]:
B =np.array([5,2,5,3,2,9,1,3])
V,C=np.unique(B,return_counts=True)
print("value of  V=" , V)
print("counting of  c=" , C)

value of  V= [1 2 3 5 9]
counting of  c= [1 2 2 2 1]


In [178]:
B =np.array([5,2,5,3,2,9,1,3])
V,C=np.unique(B,return_counts=True)
print("value of  V=" , V)
print("counting of  c=" , C)

for value,counting in zip(V,C):
    print(value,counting)



value of  V= [1 2 3 5 9]
counting of  c= [1 2 2 2 1]
1 1
2 2
3 2
5 2
9 1


In [179]:
A=np.array(["welcome to all"])
print(A)
upper_words = np.char.upper(A)
print(upper_words)

['welcome to all']
['WELCOME TO ALL']


In [180]:
A=np.array(["WELCOME TO ALL"])
print(A)
lower_words = np.char.lower(A)
print(lower_words)

['WELCOME TO ALL']
['welcome to all']


In [181]:
A=np.array(["WELCOME TO ALL"])
print(A)
title_words = np.char.title(A)
print(title_words)

['WELCOME TO ALL']
['Welcome To All']


In [182]:
A=np.array(["WELCOME TO ALL"])
print(A)
capitalize_words = np.char.capitalize(A)
print(capitalize_words)

['WELCOME TO ALL']
['Welcome to all']


In [3]:
A=np.array(["WELCOME TO ANURAJ BRO"])
print(A)
swapcase_words = np.char.swapcase(A)
print(swapcase_words)

['WELCOME TO ANURAJ BRO']
['welcome to anuraj bro']


In [183]:
A=np.array(["WELCOME TO ALL"])
print(A)
swapcase_words = np.char.swapcase(A)
print(swapcase_words)

['WELCOME TO ALL']
['welcome to all']


In [184]:
A=np.array(["welcome to all"])
print(A)
swapcase_words = np.char.swapcase(A)
print(swapcase_words)

['welcome to all']
['WELCOME TO ALL']


In [185]:
A=np.array(["WELCOME TO-ALL"])
print(A)
replace_words = np.char.replace(A, '-','#')
print(replace_words)

['WELCOME TO-ALL']
['WELCOME TO#ALL']


### Core Statistical Functions

In [186]:
import numpy as np

In [187]:
#1. Create a one-dimensional NumPy array with values from 1 to 10 and display it
A=np.arange(1,11)
print(A)

[ 1  2  3  4  5  6  7  8  9 10]


In [188]:
A=np.array([1,2,3,4,5,6,7,8,9,10])
print(A)

[ 1  2  3  4  5  6  7  8  9 10]


In [189]:
#2. Create a NumPy array using np.arange() with values from 0 to 50 with a step size of 5
A=np.arange(0,50,5)
print(A)

[ 0  5 10 15 20 25 30 35 40 45]


In [190]:
A=np.linspace(0,50,10,dtype=int)
print(A)

[ 0  5 11 16 22 27 33 38 44 50]


In [191]:
# 3. Create a two-dimensional NumPy array of shape (3, 4) filled with zero
A=np.zeros((3,4),dtype=int)
print(A) 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [192]:
#4. Create a three-dimensional NumPy array of shape (2, 3, 4) filled with ones.
A= np.ones((2, 3, 4),dtype= int)
print(A)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [193]:
#5. Create a NumPy array of length 10 where all elements are zero except the middle element, which should be 5.



In [194]:
#6. Create a NumPy array using np.arange() and reshape it into a 4×5 matrix.
A=np.arange(0,20).reshape(4,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### 5. Create a matrix where each row is numbers 1–5.

In [195]:
M = np.zeros((4,5),dtype=int)
print(M)
M[::,0:1:] = 1
M[::,1:2:] = 2
M[::,2:3:] = 3
M[::,3:4:] = 4
M[::,4:5:] = 5
print("New matrix")
print(M)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
New matrix
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [196]:
A=np.eye((3),dtype=int)
A[::2,::2]=1
print(A)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [197]:
M = np.zeros((5,5),dtype=int)
print(M)
M[::1,::2] = 1
print("New matrix")
print(M)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
New matrix
[[1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]
 [1 0 1 0 1]]


In [198]:
l = [10,9,12,5,6]
print(l)
for i in range(len(l)): 
    print(l[i])

[10, 9, 12, 5, 6]
10
9
12
5
6


In [199]:
l = [10,9,12,5,6]
print(l)
for i in range(len(l)-1,-1,-1): 
    print(l[i],end=" ")

[10, 9, 12, 5, 6]
6 5 12 9 10 

In [200]:
l = [10,9,12,5,6]
print(l)
for i in range(len(l)):
    i = -1 -i
    print(l[i],end=" ")

[10, 9, 12, 5, 6]
6 5 12 9 10 

In [201]:
A=np.eye((3),dtype=int)
A[::2,::2]= 1
print(A)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [202]:
a


array([[1, 2]])

- Common NumPy Aggregate Functions

In [ ]:
np.sum() / np.prod()np.min() / np.max()np.mean() / np.std() / np.var()np.any() / np.all()

In [16]:
Z = np.array([1,3,2,55,33,23,0,50,121,44,23])
Z=np.sum(Z)
print(Z)

355


In [21]:
Z = np.array([1,3,2,55,33,23,0,50,121,44,23])
Z=np.pro(Z)
print(Z)

0


In [22]:
Z = np.array([1,3,2,55,33,23,0,50,121,44,23])
Z=np.min(Z)
print(Z)

0


In [23]:
Z = np.array([1,3,2,55,33,23,0,50,121,44,23])
Z=np.max(Z)
print(Z)

121


In [24]:
Z = np.array([1,3,2,55,33,23,0,50,121,44,23])
Z=np.min(Z)
print(Z)

0


In [25]:
Z = np.array([1,3,2,55,33,23,0,50,121,44,23])
Z=np.std(Z)
print(Z)

34.120350922981984


In [26]:
Z = np.array([1,3,2,55,33,23,0,50,121,44,23])
Z=np.var(Z)
print(Z)

1164.1983471074377


In [27]:
Z = np.array([1,3,2,55,33,23,0,50,121,44,23])
Z=np.any(Z)
print(Z)

True


In [28]:
Z = np.array([1,3,2,55,33,23,0,50,121,44,23])
Z=np.all(Z)
print(Z)

False
